### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by coIev** [blue-bird1/xss_fuzz#1]
OS: Windows 7

Python version: 2.7.16

Steps to reproduce:  C:\Users\king\Desktop\xss_fuzz-master (1)\xss_fuzz-master>python xssfuzz.py -u "http://wafdemo.cf/?q=x"

Screenshot: https://gyazo.com/1d5eb7899dcc753d9e027da89244ba22

**Comment by blue-bird1** [comment]
Recent updates fix bugs, please git pull

**Comment by coIev** [comment]
Confirmed fixed on that part but the error still pops up at the end.

https://gyazo.com/d1026113f3bd557e1f41ee940626d13a

**Comment by blue-bird1** [comment]
I fixed the bug, but I noticed that your test url might not work. It uses JavaScript and does not return results directly.
